# Site settings
title: noyobo's Blog
email: noyobo@gmail.com
description: "GuiterScript"
permalink: /:year/:month/:day/:title.html
baseurl: ""
url: "http://noyobo.com"
atom-baseurl: "http://noyobo.com"
author: "noyobo"
github: "https://github.com/noyobo/noyobo.github.com/tree/master/"

# Build settings
# permalink: date

#pygments: true
highlighter: rouge
markdown: kramdown  # [ maruku | rdiscount | kramdown | redcarpet ]
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile
# redcarpet:
#   extensions:
#     - fenced_code_blocks
#     - no_intra_emphasis
#     - strikethrough
#     - no_intra_emphasis
#     - autolink
#     - tables
#     - with_toc_data
kramdown:
  input:            GFM
  auto_id_prefix:   ''
  auto_ids:         true
  extensions:
    - autolink
    - footnotes
    - smart
  transliterated_header_ids: false
  footnote_nr:   1
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  use_coderay:   true

  # coderay:
  #   coderay_wrap:              div
  #   coderay_line_numbers:      inline
  #   coderay_line_number_start: 1
  #   coderay_tab_width:         2
  #   coderay_bold_every:        10
  #   coderay_css:               style

duoshuo:
  comments :
    provider : duoshuo
    duoshuo :
      short_name : noyobo

navigations:
  - title: project
    class: fa fa-code
    href: http://noyobo.com/badgeboard/
  - title: about
    class: fa fa-user
    href: /about
  - title: archive
    class: fa fa-archive
    href: /archive
  - title: categories
    class: fa fa-folder
    href: /categories
  - title: tags
    class: fa fa-tags
    href: /tags
  - title: labs
    class: fa fa-bomb
    href: /labs
#  - title: 404
#    class: fa fa-coffee
#    href: /404